name = "anoplace"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/anoplace/hugo-theme-anoplace/master/LICENSE.md"
description = "anoplace corporate website theme for Hugo"
homepage = "https://github.com/anoplace/hugo-theme-anoplace/"
tags = ["", ""]
features = ["", ""]

[author]
  name = "anoplace inc"
  email = "info@ano-place.com"
  homepage = "http://www.ano-place.com"
